Fix for refreshing short-lived TLS certs.  Not configurable in this s…
TassoDigital/openapi-generator pull request #4
Opened 2022-01-03 14:53 UTC by wilsondy

…tate, in case we wanted to offer back to the community.

2022-01-05 19:00 UTC, webpepper requested changes

2022-01-05 19:44 UTC, wilsondy commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || cachedOptionsRefresh < new Date()){
Initially, "undefined < new Date()" it isn't evaluated since it shortcuts on the left hand side and ever after it is defined.

After that, I'm just trying see if the thing is old enough to warrant a reload.  I do this so we don't reload the files on ever request.

I've made some name changes and the switch to getTime() as suggested.  See what you think.

2022-01-05 19:58 UTC, webpepper requested changes

2022-01-05 19:58 UTC, webpepper commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +let nextOptionsRefresh: number = undefined;
I'm not sure how Typescript is involved here and if type checking matters, but it's an invalid definition here and on the line above. Maybe just assign an initial value of 0 and remove `undefined` out of the picture completely?

![image](https://user-images.githubusercontent.com/2255363/148280436-38241ad0-34dc-461b-b47e-5742156c22f2.png)

2022-01-05 19:58 UTC, webpepper commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || nextOptionsRefresh < new Date().getTime()){
Same here, if Typescript matter it won't be happy here. Comparing undefined and number doesn't fly in the Typescript world.

![image](https://user-images.githubusercontent.com/2255363/148280872-9a0a9c46-911d-4287-b0b3-c0183d25eb46.png)

2022-01-05 19:59 UTC, webpepper commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || cachedOptionsRefresh < new Date()){
Yeah, it makes sense. It's just one of those things where code reading doesn't flow, you gotta stop and do all those evaluations in your head. And what doesn't flow can be misinterpreted by whoever is looking at it.

2022-01-06 13:35 UTC, wilsondy commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || nextOptionsRefresh < new Date().getTime()){
It will never be zero or undefined in the comparison.  You've modified the code for the screenshot and lost the benefit of the short circuit || that is in the actual code.  The transpiler is doing the logic and recognizes that an undefined comparison is not possible.

2022-01-06 13:37 UTC, wilsondy commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +let nextOptionsRefresh: number = undefined;
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

Strict null checks are currently not turned on, so Typescript doesn't complain about the undefined number assignment.  I'm happy to set it to zero as the initial value never matters.

2022-01-06 13:51 UTC, wilsondy commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || nextOptionsRefresh < new Date().getTime()){
zero has been set.

2022-01-06 13:52 UTC, wilsondy commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +let nextOptionsRefresh: number = undefined;
zero has been set

2022-01-06 20:50 UTC, webpepper commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +                if(cachedOptions === undefined || nextOptionsRefresh < new Date().getTime()){
You may be right, the compiler is smarter than me in this case probably 😄

2022-01-06 20:51 UTC, webpepper requested changes

2022-01-06 20:51 UTC, webpepper commented on modules/openapi-generator/src/main/resources/typescript-nestjs/api.module.mustache
> +let cachedOptions: HttpModuleOptions = undefined;
I think this is the last 1️⃣ 

```suggestion
let cachedOptions: HttpModuleOptions | undefined = undefined;
```

2022-01-06 21:45 UTC, webpepper approved these changes

2022-01-06 22:16 UTC, merged